### ISSUE TITLE
Add english lecture mateials

### ISSUE THREAD

**Issue by alanverdugo** [alanverdugo/gilbert#1]
Since Gilbert is an educational application, we want students to be able to read and study at least *some* lectures without an Internet connection.

We need short lectures in (text format) about electricity and magnetism. It can be any topic and electricity and magnetism, from a simple introduction (including history) to advanced knowledge.

Currently, we have some `.rst` lectures in [https://github.com/alanverdugo/gilbert/tree/master/assets/chapters](assets/chapters), but they are in Spanish (taken from wikibooks: https://es.wikibooks.org/wiki/Electricidad/%C3%8Dndice). You can refer to them as examples of what we need.

Ideally, this material should be in `.rst` format, and any images or diagrams you include should be free to use. Any material will be subject to Gilbert's license (which is the permissive Apache 2.0 license). Remember this is a free educational application.

Any contributor will be included in the "About" section of the mobile application. Please state how you want to be referred to (name, nickname, github user, email, etc).

If you don't want or know how to contribute using GitHub, you can send the materials to factorpolar@gmail.com and I will add them to the application for you. Thanks!

**Comment by peppermint-juli** [comment]
Hello @alanverdugo ! I love this project and would love to help out, but this issue is huge (or so I  feel). Wouldn't it be easier to translate the chapters you already have in Spanish to english? I can help with that. Either way, how are going to differentiate the english chapters from the Spanish ones (and maybe other languages later on)? Separate them in folders?

**Comment by alanverdugo** [comment]
Hello @PeppermintNDaisies ! All great and valid questions!
Yes, the easy path would be to just translate the Spanish chapters to English. If you could help with that (or at least with some of them), it would be amazing! I can open a separate issue for each chapter if you think that would be better or easier.
I will place the Spanish chapters in a separate folder and the English ones will be the default for now.

Some context: My ultimate goal is to have the entire application translated to several languages, so the students could just choose the one they prefer.
However, I noticed that a Spanish-only app is less popular and usable than an English-only app. So the plan would be to translate everything to English and slowly add more languages (Spanish being the first one, probably). Hopefully, we can reach and help more students in this way, since they are probably speaking and/or studying English already.

Also, if the application is in English, it would be easier to get help from other collaborators/programmers, which could add more functionality and content.
Let me know what you think!

**Comment by peppermint-juli** [comment]
Absolutely agree with the objective! Yeah, I think it would be better to separate each chapter translation to english (and then other languages) by issues, that way people can grab what they can. 
I'll start working on the english translations then!

**Comment by alanverdugo** [comment]
Hello @PeppermintNDaisies !, I've created 3 issues, one for the translation of each chapter.
Feel free to assign any of them to yourself:
https://github.com/alanverdugo/gilbert/issues/2
https://github.com/alanverdugo/gilbert/issues/3
https://github.com/alanverdugo/gilbert/issues/4

I've marked them for hacktoberfest in case you want the reward. I will close this issue since the new issues will cover the translation. Thanks!
